# Generated by Django 4.1.2 on 2022-11-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_playerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
