# Generated by Django 4.1.2 on 2022-11-12 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScorecardId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=55)),
                ('date', models.DateTimeField()),
                ('players', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('score', models.IntegerField()),
                ('ScorecardId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecards.scorecardid')),
                ('playerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecards.hole')),
            ],
        ),
    ]
