# Generated by Django 4.1.2 on 2022-11-14 21:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scorecards', '0003_rename_scorecardid_scorecard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorecard',
            name='players',
        ),
        migrations.AddField(
            model_name='scorecard',
            name='players',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
