# Generated by Django 4.1.2 on 2022-11-16 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorecards', '0004_remove_scorecard_players_scorecard_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hole',
            name='scorecard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holes', to='scorecards.scorecard'),
        ),
    ]
