# Generated by Django 4.1.2 on 2022-11-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecards', '0005_alter_hole_scorecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='hole',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
