# Generated by Django 4.1.2 on 2022-11-18 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorecards', '0006_scorecard_hole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorecard',
            name='hole',
        ),
    ]
