# Generated by Django 4.1.2 on 2022-11-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecards', '0007_remove_scorecard_hole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hole',
            name='score',
        ),
        migrations.AddField(
            model_name='hole',
            name='player1Score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='hole',
            name='player2Score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='hole',
            name='player3Score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='hole',
            name='player4Score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
