# Generated by Django 4.1.2 on 2022-11-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecards', '0008_remove_hole_score_hole_player1score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hole',
            name='hole',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
